# Generated by Django 5.0.7 on 2024-08-20 12:06

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, validators=[shop.models.validate_input]),
        ),
    ]
